#!/bin/sh -e

# shellcheck source=/dev/null

log() {
    fmt="$1"
    shift
    # shellcheck disable=2059
    printf "\e[1m==> $fmt\e[m\n" "$@"
}

error() {
    fmt="$2"
    errcode="$1"
    shift 2
    # shellcheck disable=2059
    printf "\e[1;31m$fmt\n" "$@"
    exit "$errcode"
}

pkg_search() {
    IFS=:
    for path in $PKG_PATH; do
        if [ -d "$path/$1" ]; then
            echo "$path/$1"
            return 0
        fi
    done
    return 1
}

fetch() {
    IFS= read -r url name << EOF
$1
EOF
    case $url in
        *://*)
            cd "/usr/pkg/sources"
            wget "$url"
            cd "$3"
            tar xf "/usr/pkg/sources/$(basename "$url")"
            ;;
        *)
            cp "$2/$url" "$3/$url"
            ;;
    esac
    # shellcheck disable=2015
    [ -n "$name" ] && mv "$3/$(basename "${url%.tar*}")" "$3/$name" || true
}

pkg_build() {
    dir=$(pkg_search "$1")
    . "$dir/karafile"

    # shellcheck disable=2154
    if [ -z "$depends" ]; then
        IFS=
        for pkg in $depends; do
            pkg -b "$pkg"
            pkg -i "$pkg"
        done
    fi
    builddir="/usr/pkg/build/$1-${version:?}"
    rootdir="/usr/pkg/root/$1-$version"
    mkdir -p "$builddir"
    mkdir -p "$rootdir"

    echo "${sources:?}" | while read -r source; do
        fetch "$source" "$dir" "$builddir"
    done

    src=$(echo "$sources" | { read -r src; basename "${src%.tar*}"; })
    cp -r "$builddir/$src"/* "$builddir/"
    cd "$builddir"
    build "$rootdir"
    exit
}

pkg_install() {
    dir=$(pkg_search "$1")
    . "$dir/karafile"

    [ ! -d "/usr/pkg/root/$1-${version:?}" ] && error "Package not built"

    mkdir -p "/usr/pkg/manifests/$1/"
    echo "$version" > "/usr/pkg/manifests/$1/version"
    find "/usr/pkg/root/$1-$version" > "/usr/pkg/manifests/$1/files"

    while read -r file; do
        cp "/usr/pkg/root/$1-$version/$file" "/$file"
    done < "/usr/pkg/manifests/$1/files"
}

pkg_uninstall() {
    while read -r file; do
        rm "/$file"
    done < "/usr/pkg/manifests/$1/files"
    rm -r "/usr/pkg/manifests/$1"
}

pkg_clean() {
    rm -r "/usr/pkg/build/$1-*"
    rm -r "/usr/pkg/root/$1-*"
}

case "$1" in
    -b)
        shift
        for pkg in "$@"; do
            pkg_build "$pkg"
        done
        ;;
    -i)
        shift
        for pkg in "$@"; do
            pkg_install "$pkg"
        done
        ;;
    -u)
        shift
        for pkg in "$@"; do
            pkg_uninstall "$pkg"
        done
        ;;
    -c)
        shift
        for pkg in "$@"; do
            pkg_uninstall "$pkg"
        done
        ;;
esac
