#!/bin/sh -e

# shellcheck source=/dev/null

pkg_search() {
    IFS=:
    for path in $PKG_PATH; do
        if [ -d "$path/$1" ]; then
            echo "$path/$1"
            return 0
        fi
    done
    return 1
}

fetch() {
    IFS= read -r url name << EOF
$1
EOF
    case $url in
        *://*)
            cd "/usr/pkg/sources"
            wget "$url"
            cd "$2"
            tar xf "/usr/pkg/sources/$(basename "$url")"
            ;;
        *)
            cp "$1/$url" "$2"
            ;;
    esac
    # shellcheck disable=2015
    [ -n "$name" ] && mv "$2/$(basename "$url")" "$2/$name" || true
}

pkg_build() {
    dir=$(pkg_search "$1")
    . "$dir/karafile"

    builddir="/usr/pkg/build/$1-${version:?}"
    rootdir="/usr/pkg/root/$1-$version"
    mkdir "$builddir"
    mkdir "$rootdir"

    echo "${sources:?}" | while read -r source; do
        fetch "$source" "$dir" "$builddir"
    done

    cd "$builddir"
    build "$rootdir"
    exit
}

pkg_install() {
    dir=$(pkg_search "$1")
    . "$dir/karafile"

    [ ! -d "/usr/pkg/root/$1-${version:?}" ] &&
        echo "Package not built" && exit 1

    mkdir -p "/usr/pkg/manifests/$1/"
    echo "$version" > "/usr/pkg/manifests/$1/version"
    find "/usr/pkg/root/$1-$version" > "/usr/pkg/manifests/$1/files"
    while read -r file; do
        cp "/usr/pkg/root/$1-$version/$file" "/$file"
    done < "/usr/pkg/manifests/$1/files"
}

pkg_uninstall() {
    while read -r file; do
        rm "/$file"
    done < "/usr/pkg/manifests/$1/files"
    rm -r "/usr/pkg/manifests/$1"
}

case "$1" in
    -b)
        pkg_build "$2"
        ;;
    -i)
        pkg_install "$2"
        ;;
    -u)
        pkg_uninstall "$2"
        ;;
esac
